export const languageOptions = [
  { value: 'Abkhazian', label: 'Abkhazian' },
  { value: 'Afar', label: 'Afar' },
  { value: 'Afrikaans', label: 'Afrikaans' },
  { value: 'Akan', label: 'Akan' },
  { value: 'Albanian', label: 'Albanian'},
  { value: 'Amharic', label: 'Amharic' },
  { value: 'Arabic', label: 'Arabic' },
  { value: 'Aragonese', label: 'Aragonese' },
  { value: 'Armenian', label: 'Armenian' },
  { value: 'Assamese', label: 'Assamese' },
  { value: 'Avaric', label: 'Avaric' },
  { value: 'Avestan', label: 'Avestan' },
  { value: 'Aymara', label: 'Aymara' },
  { value: 'Azerbaijani', label: 'Azerbaijani' },
  { value: 'Bambara', label: 'Bambara' },
  { value: 'Bashir', label: 'Bashir' },
  { value: 'Basque', label: 'Basque' },
  { value: 'Belarusian', label: 'Belarusian' },
  { value: 'Bengali', label: 'Bengali' },
  { value: 'Bihari languages', label: 'Bihari languages' },
  { value: 'Bislama', label: 'Bislama' },
  { value: 'Bosnian', label: 'Bosnian' },
  { value: 'Breton', label: 'Breton' },
  { value: 'Bulgarian', label: 'Bulgarian' },
  { value: 'Burmese', label: 'Burmese' },
  { value: 'Catalan,Valencian', label: 'Catalan,Valencian' },
  { value: 'Central Khmer', label: 'Central Khmer' },
  { value: 'Chamorro', label: 'Charmorro' },
  { value: 'Chechen', label: 'Chechen' },
  { value: 'Chichewa,Chewa,Nyanja', label: 'Chichewa,Chewa,Nyanja' },
  { value: 'Chinese', label: 'Chinese' },
  { value: 'Church salvonic,Old Bulgarian,Old Church Slavonic', label: 'Church salvonic,Old Bulgarian,Old Church Slavonic' },
  { value: 'Chuvash', label: 'Chuvash' },
  { value: 'Cornish', label: 'Cornish' },
  { value: 'Corsican', label: 'Corsican' },
  { value: 'Cree', label: 'Cree' },
  { value: 'Croatian', label: 'Croatian' },
  { value: 'Czech', label: 'Czech' },
  { value: 'Danish', label: 'Danish' },
  { value: 'Divehi,Dhivehi,MAldivian', label: 'Divehi,Dhivehi,MAldivian' },
  { value: 'Dutch,Flemish', label: 'Dutch,Flemish' },
  { value: 'Dzongkha', label: 'Dzongkha' },
  { value: 'English', label: 'English' },
  { value: 'Esperanto', label: 'Esperanto' },
  { value: 'Estonian', label: 'Estonian' },
  { value: 'Ewe', label: 'Ewe' },
  { value: 'Faroese', label: 'Faroese' },
  { value: 'Fijian', label: 'Fijian' },
  { value: 'Finnish', label: 'Finnish' },
  { value: 'French', label: 'French' },
  { value: 'Fulah', label: 'Fulah' },
  { value: 'Gaelic,Scottish Gaelic', label: 'Gaelic,Scottish Gaelic' },
  { value: 'Galician', label: 'Galician' },
  { value: 'Ganda', label: 'Ganda' },
  { value: 'Georgian', label: 'Georgian' },
  { value: 'German', label: 'German' },
  { value: 'Gikuyu,Kikuyu ', label: 'Gikuyu,Kikuyu' },
  { value: 'Greek(Modern)', label: 'Greek(Modern)' },
  { value: 'Greenlandic, Kalaallisut', label: 'Greenlandic, Kalaallisut' },
  { value: 'Guarani', label: 'Guarani' },
  { value: 'Gujarati', label: 'Gujarati' },
  { value: 'Haitian, Haitian Creole', label: 'Haitian, Haitian Creole' },
  { value: 'Hausa', label: 'Hausa' },
  { value: 'Hebrew', label: 'Hebrew' },
  { value: 'Herero', label: 'Herero' },
  { value: 'Hindi', label: 'Hindi' },
  { value: 'Hiri Motu', label: 'Hiri Motu' },
  { value: 'Hungarian', label: 'Hungarian' },
  { value: 'Icelandic', label: 'Icelandic' },
  { value: 'Ido', label: 'Ido' },
  { value: 'Igbo', label: 'Igbo' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'Interlingua(International Auxiliary Languange Association', label: 'Interlingua(International Auxiliary Languange Association' },
  { value: 'Interlingue', label: 'Interlingue' },
  { value: 'Inuktitut', label: 'Inkutitut' },
  { value: 'Inupiaq', label: 'Inupiaq' },
  { value: 'Irish', label: 'Irish' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Japenese', label: 'Japenese' },
  { value: 'Javanese', label: 'Javenese' },
  { value: 'Kannada', label: 'Kannada' },
  { value: 'Kanuri', label: 'Kanuri' },
  { value: 'Kashmiri', label: 'Kashmiri' },
  { value: 'Kazakh', label: 'Kazakh' },
  { value: 'Kinyarwanda', label: 'Kinyarwanda' },
  { value: 'Komi', label: 'Komi' },
  { value: 'Kongo', label: 'Kongo' },
  { value: 'Koreon', label: 'Koreon' },
  { value: 'Kwanyama, kuanyama', label: 'Kwanyama, kuanyama' },
  { value: 'Kurdish', label: 'Kurdish' },
  { value: 'Kyrgyz', label: 'Kyrgyx' },
  { value: 'Lao', label: 'Lao' },
  { value: 'Latin', label: 'Latin' },
  { value: 'Latvian', label: 'Latvian' },
  { value: 'Letzeburgesch,Luxembourgish', label: 'Letzeburgesch,Luxembourgish' },
  { value: 'Limburgish,Limburgan,Limburger', label: 'Limburgish,Limburgan,Limburger' },
  { value: ' Lingala', label: 'Lingala' },
  { value: 'Lithuanian', label: 'Lithuanian' },
  { value: 'Luba-Katanga', label: 'Luba-Katanga' },
  { value: 'Macedonian', label: 'Macedonian' },
  { value: 'Malagasy', label: 'Malagasy' },
  { value: 'Malay', label: 'Malay' },
  { value: 'Malayalam', label: 'Malayalam' },
  { value: 'Maltese', label: 'Maltese' },
  { value: 'Manx', label: 'Manx' },
  { value: 'Maori', label: 'Maori' },
  { value: 'Marathi', label: 'Marathi' },
  { value: 'Marshallese', label: 'Marshallese' },
  { value: 'Moldovan,Moldavian,Romanian', label: 'Moldovan,Moldavian,Romanian' },
  { value: 'Mangolian', label: 'Mangolian' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Navajo,Navaho', label: 'Navajo,Navaho' },
  { value: 'Northern Ndebele', label: 'Northern Ndebele' },
  { value: 'Ndonga', label: 'Ndonga' },
  { value: 'Nepali', label: 'Nepali' },
  { value: 'Northern Sami', label: 'Northern Sami' },
  { value: 'Norwegian', label: 'Norwegian' },
  { value: 'Norwegian Bokmal', label: 'Norwegian Bokmal' },
  { value: 'Norwegian Nynorsk', label: 'Norwegian Nynorsk' },
  { value: 'Nuosu,Sichuan Yi', label: 'Nuosu,Sichuan Yi' },
  { value: 'Occitan(post 1500)', label: 'Occitan(post 1500)' },
  { value: 'Ojibwa', label: 'Ojibwa' },
  { value: 'Oriya', label: 'Oriya' },
  { value: 'Oromo', label: 'Oromo' },
  { value: 'Ossetian,Ossetic', label: 'Ossetian,Ossetic' },
  { value: 'Pali', label: 'Pali' },
  { value: 'Panjabi,Punjabi', label: 'Panjabi,Punjabi' },
  { value: 'Pashto,Pushto', label: 'Pashto,Pushto' },
  { value: 'Persian', label: 'Persian' },
  { value: 'Polish', label: 'Polish' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Quechua', label: 'Quechua' },
  { value: 'Romansh', label: 'Romansh' },
  { value: 'Rundi', label: 'Rundi' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Samoan', label: 'Samoan' },
  { value: 'Sango', label: 'Sango' },
  { value: 'Sanskrit', label: 'sanskrit' },
  { value: 'Sardinian', label: 'Sardinian' },
  { value: 'Serbian', label: 'Serbian' },
  { value: 'Shona', label: 'Shona' },
  { value: 'Sindhi', label: 'Sindhi' },
  { value: 'Sinhala,Sinhalese', label: 'Sinhala,Sinhalese' },
  { value: 'Slovak', label: 'Slovak' },
  { value: 'Slovenian', label: 'slovenian' },
  { value: 'Somali', label: 'Somali' },
  { value: 'Sotho, Southern', label: 'Sotho, Southern' },
  { value: 'South Ndebele', label: 'South Ndebele' },
  { value: 'Spanish,Castilian', label: 'Spanish,Castilian' },
  { value: 'Sundanese', label: 'Sundanese' },
  { value: 'Swahili', label: 'Swahili' },
  { value: 'Swati', label: 'Swati' },
  { value: 'Swedish', label: 'Swedish' },
  { value: 'Tagalog', label: 'Tagalog' },
  { value: 'Tahitian', label: 'Tahitian' },
  { value: 'Tajik', label: 'Tajik' },
  { value: 'Tamil', label: 'Tamil' },
  { value: 'Tatar', label: 'Tatar' },
  { value: 'Telugu', label: 'elugu' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Tibetan', label: 'Tibetan' },
  { value: 'Tigrinya', label: 'Tigrinya' },
  { value: 'Tonga(Tonga Islands)', label: 'Tonga(Tonga Islanda)' },
  { value: 'Tsonga', label: 'Tsonga' },
  { value: 'Tswana', label: 'Tswana' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Turkmen', label: 'Turkmen' },
  { value: 'Twi', label: 'Twi' },
  { value: 'Uighur,Uyghur', label: 'Uighur,Uyghur' },
  { value: 'Ukrainian', label: 'Ukrainian' },
  { value: 'Urdu', label: 'Urdu' },
  { value: 'Uzbek', label: 'Uzbek' },
  { value: 'Venda', label: 'Venda' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Volap_k', label: 'Volap_k' },
  { value: 'Walloon', label: 'Walloon' },
  { value: 'Welsh', label: 'Welsh' },
  { value: 'Western Frisian', label: 'Western Frisian' },
  { value: 'Wolof', label: 'Wolof' },
  { value: 'Xhosa', label: 'Xhosa' },
  { value: 'Yiddish', label: 'Yiddish' },
  { value: 'Yoruba', label: 'Yoruba' },
  { value: 'Zhuang,Chuang', label: 'Zhuang,Chuang' },
  { value: 'Zulu', label: 'Zulu' },
  

];

export const fontOptions=[
  { value: 'cyrillic', label: 'cyrillic' },
  { value: 'cyrillic-ext', label: 'cyrillic-ext' },
  { value: 'greek', label: 'greek' },
  { value: 'greek-ext', label: 'greek-ext' },
  { value: 'latin-ext', label: 'latin-ext' },
  { value: 'vietnamese', label: 'vietnamese' },
  


];