export const CLITYPENAME = {
  HelpscoutCLI: "Help Scout",
  GmailCLI: "Gmail",
  GoogleCalendarCLI: "Google Calendar",
  GoogleDriveCLI: "Google Drive",
  GoogleSheetCLI: "Google Sheets",
  CampaignMonitorCLI: "Campaign Monitor",
  AsanaCLI: "Asana",
  ActiveCampaignCLI: "Active Campaign",
  HubspotCLI: "HubSpot",
  MailchimpCLI: "Mailchimp",
  TrelloCLI: "Trello",
  SlackCLI: "Slack",
  MeistertaskCLI: "MeisterTask",
  ConvertkitCLI: "ConvertKit",
  FreshdeskCLI: "Freshdesk",
  DropboxCLI: "Dropbox",
  MoosendCLI: "Moosend",
  MailerliteCLI: "Mailerlite",
  GoToWebinarCLI: "GoToWebinar",
  ZendeskCLI: "Zendesk",
  MailshakeCLI: "MailShake",
  KeapCLI: "Keap InfusionSoft",
  IntercomCLI: "Intercom",
  ZohoCLI: "Zoho CRM",
  DripCLI: "Drip",
  ClicksendCLI: "ClickSend",
  SendInBlueCLI: "SendInBlue",
  DiscordCLI: "Discord",
  TelegramCLI: "Telegram",
  MixPanelCLI:"MixPanel",
  CustomerioCLI:"Customer.io",
  GetResponseCLI:"GetResponse",
  ClickUpCLI:"ClickUp",
  CalendlyCLI:"Calendly",
  TypeFormCLI:"TypeForm",
  DocuSignCLI: "DocuSign",
  StoryChiefCLI:"StoryChief",
  SwellCLI: "Swell",
  XeroCLI: "Xero",
  MondayCLI: "Monday.com",
  PipedriveCLI: "Pipedrive",
  NotionCLI: "Notion",
  SurveySparrowCLI: "SurveySparrow",
  FollowUpBossCLI: "FollowUpBoss",
  LionDeskCLI: "LionDesk",
  BombBombCLI: "BombBomb",
  GoogleContactCLI: "Google Contact",
  PandaDocCLI: "PandaDoc"
};

export const CLINAME = {
  SlackCLI: "SlackCLI",
  ActiveCampaignCLI: "ActiveCampaignCLI",
  HelpscoutCLI: "HelpscoutCLI",
  DropboxCLI: "DropboxCLI",
  GoToWebinarCLI: "GoToWebinarCLI",
  GmailCLI: "GmailCLI",
  GoogleDriveCLI: "GoogleDriveCLI",
  GoogleCalendarCLI: "GoogleCalendarCLI",
  GoogleSheetCLI: "GoogleSheetCLI",
  KeapCLI: "KeapCLI",
  IntercomCLI: "IntercomCLI",
  ZohoCLI: "ZohoCLI",
  DripCLI: "DripCLI",
  ClicksendCLI: "ClicksendCLI",
  DocuSignCLI: "DocuSignCLI",
  XeroCLI: "XeroCLI",
  LionDeskCLI: "LionDeskCLI",
  GoogleContactCLI: "GoogleContactCLI"
};
